import funcoes
funcoes.menu()

'''
CHECKLIST:

#IDENTIFICAR QUEM GANHOU ## CONCLUIDO
#NÃO SOBRESCREVER O OUTRO ## CONCLUÍDO
#PODER JOGAR CONTRA O COMPUTADOR CONCLUIDO
#diminuir o numero de linhas: 178-> 107 -> 97
'''
